### ISSUE TITLE
Issue when trying to login 

### ISSUE THREAD

**Issue by PiglinPlayz** [open-template-hub/mail-server-template#24]
<p align="center"><a href="https://opentemplatehub.com"><img src="https://raw.githubusercontent.com/open-template-hub/open-template-hub.github.io/master/assets/logo/brand-logo-broken.png" alt="Logo" width=150></a></p>
<h2 align="center">Open Template Hub - Bug Report</h2>

## Description

Define the problem clearly

I'm getting this error when i try to login.

{"error":{"code":400,"message":"CONFIGURATION_NOT_FOUND","errors":[{"message":"CONFIGURATION_NOT_FOUND","domain":"global","reason":"invalid"}]}}

## Supplementary Info
Host = https:/replit.com / https://repl.it
https://mail.playpiglin.net

<table align="right"><tr><td><a href="https://opentemplatehub.com"><img src="https://raw.githubusercontent.com/open-template-hub/open-template-hub.github.io/master/assets/logo/brand-logo.png" width="50px" alt="oth"/></a></td><td><b>Open Template Hub © 2021</b></td></tr></table>

**Comment by fatihturker** [comment]
Hi @PiglinPlayz,

Which provider are you using? (Firebase?)

This issue seems to be related with the service provider.
There might be extra permission / configuration needed on your provider.

Could you please review below link?
https://www.reddit.com/r/Firebase/comments/fd19x5/whats_causing_firebase_code_400_message/

Regards,
Fatih
